MVC/Controllers/DbController.cs
using BLL.DAL;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace MVC.Controllers
{
    public class DbController : Controller
    {
        private readonly Db _db;

        public DbController(Db db)
        {
            _db = db;
        }

        public IActionResult Seed()
        {
            _db.Users.RemoveRange(_db.Users.ToList());
            _db.Roles.RemoveRange(_db.Roles.ToList());

            _db.Roles.Add(new Role()
            {
                Name = "Admin",
                Users = new List<User>()
                {
                    new User()
                    {
                        UserName = "admin",
                        Password = "admin",
                        IsActive = true
                    }
                }
            });
            _db.Roles.Add(new Role()
            {
                Name = "User",
                Users = new List<User>()
                {
                    new User()
                    {
                        UserName = "user",
                        Password = "user",
                        IsActive = true
                    }
                }
            });

            _db.SaveChanges();

            return Content("<label style=\"color:red;\">Database seed successful.</label>", "text/html", Encoding.UTF8);
        }
    }
}

MVC/Controllers/EvaluatedsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BLL.Controllers.Bases;
using BLL.Services.Bases;
using BLL.Models;
using BLL.DAL;
using Microsoft.AspNetCore.Authorization;

// Generated from Custom Template.

namespace MVC.Controllers
{
    public class EvaluatedsController : MvcController
    {
        // Service injections:
        private readonly IService<Evaluated, EvaluatedModel> _evaluatedService;

        /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
        //private readonly IService<{Entity}, {Entity}Model> _{Entity}Service;

        public EvaluatedsController(
			IService<Evaluated, EvaluatedModel> evaluatedService

            /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
            //, IService<{Entity}, {Entity}Model> {Entity}Service
        )
        {
            _evaluatedService = evaluatedService;

            /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
            //_{Entity}Service = {Entity}Service;
        }

        protected void SetViewData()
        {
            // Related items service logic to set ViewData (Record.Id and Name parameters may need to be changed in the SelectList constructor according to the model):
            
            /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
            //ViewBag.{Entity}Ids = new MultiSelectList(_{Entity}Service.Query().ToList(), "Record.Id", "Name");
        }

        // GET: Evaluateds
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            // Get collection service logic:
            var list = _evaluatedService.Query().ToList();
            return View(list);
        }

        // GET: Evaluateds/Details/5
        public IActionResult Details(int id)
        {
            // Get item service logic:
            var item = _evaluatedService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // GET: Evaluateds/Create
        public IActionResult Create()
        {
            SetViewData();
            return View();
        }

        // POST: Evaluateds/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(EvaluatedModel evaluated)
        {
            if (ModelState.IsValid)
            {
                // Insert item service logic:
                var result = _evaluatedService.Create(evaluated.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index), new { id = evaluated.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(evaluated);
        }

        // GET: Evaluateds/Edit/5
        public IActionResult Edit(int id)
        {
            // Get item to edit service logic:
            var item = _evaluatedService.Query().SingleOrDefault(q => q.Record.Id == id);
            SetViewData();
            return View(item);
        }

        // POST: Evaluateds/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EvaluatedModel evaluated)
        {
            if (ModelState.IsValid)
            {
                // Update item service logic:
                var result = _evaluatedService.Update(evaluated.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = evaluated.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(evaluated);
        }

        // GET: Evaluateds/Delete/5
        public IActionResult Delete(int id)
        {
            // Get item to delete service logic:
            var item = _evaluatedService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // POST: Evaluateds/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // Delete item service logic:
            var result = _evaluatedService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Controllers/EvaluationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BLL.Controllers.Bases;
using BLL.Services.Bases;
using BLL.Models;
using BLL.DAL;
using Microsoft.AspNetCore.Authorization;

// Generated from Custom Template.

namespace MVC.Controllers
{
    public class EvaluationsController : MvcController
    {
        // Service injections:
        private readonly IService<Evaluation, EvaluationModel> _evaluationService;
        private readonly IService<User, UserModel> _userService;

        /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
        //private readonly IService<{Entity}, {Entity}Model> _{Entity}Service;

        public EvaluationsController(
			IService<Evaluation, EvaluationModel> evaluationService
            , IService<User, UserModel> userService

            /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
            //, IService<{Entity}, {Entity}Model> {Entity}Service
        )
        {
            _evaluationService = evaluationService;
            _userService = userService;

            /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
            //_{Entity}Service = {Entity}Service;
        }

        protected void SetViewData()
        {
            // Related items service logic to set ViewData (Record.Id and Name parameters may need to be changed in the SelectList constructor according to the model):
            ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Record.Id", "Name");
            
            /* Can be uncommented and used for many to many relationships. Entity must be replaced with the related entiy name in the controller and views. */
            //ViewBag.{Entity}Ids = new MultiSelectList(_{Entity}Service.Query().ToList(), "Record.Id", "Name");
        }

        // GET: Evaluations
        [AllowAnonymous]

        public IActionResult Index()
        {
            // Get collection service logic:
            var list = _evaluationService.Query().ToList();
            return View(list);
        }

        // GET: Evaluations/Details/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(int id)
        {
            // Get item service logic:
            var item = _evaluationService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // GET: Evaluations/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create()
        {
            SetViewData();
            return View();
        }

        // POST: Evaluations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EvaluationModel evaluation)
        {
            if (ModelState.IsValid)
            {
                // Insert item service logic:
                var result = _evaluationService.Create(evaluation.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = evaluation.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(evaluation);
        }

        // GET: Evaluations/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id)
        {
            // Get item to edit service logic:
            var item = _evaluationService.Query().SingleOrDefault(q => q.Record.Id == id);
            SetViewData();
            return View(item);
        }

        // POST: Evaluations/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EvaluationModel evaluation)
        {
            if (ModelState.IsValid)
            {
                // Update item service logic:
                var result = _evaluationService.Update(evaluation.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = evaluation.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(evaluation);
        }

        // GET: Evaluations/Delete/5

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            // Get item to delete service logic:
            var item = _evaluationService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // POST: Evaluations/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // Delete item service logic:
            var result = _evaluationService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Controllers/UsersController.cs
using BLL.Controllers.Bases;
using BLL.DAL;
using BLL.Models;
using BLL.Services.Bases;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MVC.Controllers
{
    public class UsersController : MvcController
    {
        private readonly IService<User, UserModel> _userService;

        public UsersController(IService<User, UserModel> userService)
        {
            _userService = userService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var userModel = _userService.Query().SingleOrDefault(u => u.Record.UserName == user.Record.UserName &&
                    u.Record.Password == user.Record.Password && u.Record.IsActive);
                if (userModel is not null)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, userModel.UserName),
                        new Claim(ClaimTypes.Role, userModel.Role),
                        new Claim("Id", userModel.Record.Id.ToString())
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(principal, new AuthenticationProperties()
                    {
                        IsPersistent = true
                    });
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

MVC/Views/Shared/_DateTimePicker.cshtml
@* https://xdsoft.net/jqplugins/datetimepicker *@

<link href="~/lib/jquery-datetimepicker/jquery.datetimepicker.min.css" rel="stylesheet" />
<script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.full.min.js"></script>

<script>
    $(function () {
        $(".datetimepicker").datetimepicker({
            // for using only date
            // timepicker: false,
            // format: 'm/d/Y'

            // for using date with time
            timepicker: true,
            format: 'm/d/Y H:i'
        });
    });
</script>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @AppSettings.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@AppSettings.Title</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Db" asp-action="Seed">Seed Database</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Evaluations" asp-action="Index">Evaluations</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evaluateds" asp-action="Index">Evaluateds</a>
                            </li>
                        }
                    </ul>

                    <!-- User: -->
                    <div class="navbar-text">
                        <ul class="navbar-nav me-auto">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item pt-2">
                                    <span class="text-primary">@User.Identity.Name</span>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>